taskl:
  mongodb:
    image: mongo:5.0.5
  jwt:
    signing-key: VW1AHxycm69njF5s03rJP1LJONX0EGh6rgsbc4fehAaqYR6gcx
server:
  servlet:
    context-path: /api
logging:
  level:
    org:
      springframework:
        security: DEBUG
